config/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('posts/', include('posts.urls')), 
]

pages/urls.py
from django.urls import path
from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

posts/urls.py
from django.urls import path 
from .views import PostListView, PostDetailView, PostCreateView


urlpatterns = [
    path('', PostListView.as_view(), name="posts_list"),
    path('<int:pk>/', PostDetailView.as_view(), name="post_detail"),
    path('new/', PostCreateView.as_view(), name="post_new"), 
]

pages/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.urls import reverse

class Post(models.Model):
    title = models.TextField()
    body = models.TextField()

    def __str__(self):
        return self.title[:50]
    
    def get_absolute_url(self):
        return reverse("post_detail", args=[self.id])

pages/views.py
from django.views.generic import TemplateView



class HomePageView(TemplateView):
    template_name = "home.html"

posts/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from .models import Post 


class PostListView(ListView):
    template_name ="post_list.html"
    model = Post 
    paginate_by= 20 

class PostDetailView(DetailView):
    template_name = "post_detail.html"
    model = Post 

class PostCreateView(CreateView):
    template_name = "post_new.html"
    model = Post 
    fields = ["title", "body"]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} Home page {% endblock title%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Home Page</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts_list' %}">View Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'post_new' %}">Create post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled">Disabled</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div style=margin-top:5px;>
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}



{% block title %}Home{% endblock title %}

{% block content %}
<h1>Write your messages here</h1>
{% endblock content %}

templates/post_detail.html
{% extends 'base.html' %}

{% block title%} Post #{{ post.id }} {% endblock title%}

{% block content%}
<h1>{{ post.title }}</h1>
<strong>Post #{{ post.id }} </strong>
<p>{{ post.body }} </p>
<a href="{% url 'posts_list' %}">Back</a>
{% endblock content%}

templates/post_list.html
{% extends 'base.html' %}

{% block title%} Posts {% endblock title%}

{% block content %}
<ul>
    <div class="d-flex" felx-row flex wrap bd-highlight mb-3>
        {% for post in post_list %}

        <div class="card message">
            <div class="card-body">
                <h5 class="card-title">{{ post.title }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">Message #{{ post.id }}</h6>
                <p class="card-text"> {{ post.body|truncatechars:128 }}</p>
                <a href="{% url 'post_detail' post.id %}" class="btn card-button">Read more...</a>
            </div>
        </div>

        {% endfor %}
    </div>

</ul>

{% endblock content %}

templates/post_new.html
{% extends 'base.html' %}

{% block title%} Create post {% endblock title%}

{% block content%}
<div class="container create-form">
    <h1> Create Post</h1>

    <form method="POST">
        {% csrf_token %}
        <label for="id_title">Title</label>
        <input type="text" name="title" id="id_title" class="create-form-input"><br>
        <label for="id_body">Body:</label>
        <textarea name="body" cols="40" rows="10" required="" id="id_body" class="create-form-input"></textarea>
        <input type="submit" value="Create" class="btn create-button">

    </form>
</div>

{% endblock content %}